version: "3"

set: [pipefail, errexit, nounset]

vars:
  WSBRIDGE_URL: ws://localhost:8080/sms/ws
  WSBRIDGE_NUMBER_SELF: +11234567890
  WSBRIDGE_NUMBER_SERVER: +19876543210
  PORT: 5000

tasks:
  default:
    deps: [dev]

  dev:
    deps: [generate-ts-proto]
    env:
      VITE_WSBRIDGE_URL: "{{ .WSBRIDGE_URL }}"
      VITE_WSBRIDGE_NUMBER_SELF: "{{ .WSBRIDGE_NUMBER_SELF }}"
      VITE_WSBRIDGE_NUMBER_SERVER: "{{ .WSBRIDGE_NUMBER_SERVER }}"
    cmds:
      - vite --clearScreen=false --port="$PORT"

  build:
    deps: [generate-ts-proto]
    env:
      VITE_WSBRIDGE_URL: "{{ .WSBRIDGE_URL }}"
      VITE_WSBRIDGE_NUMBER_SELF: "{{ .WSBRIDGE_NUMBER_SELF }}"
      VITE_WSBRIDGE_NUMBER_SERVER: "{{ .WSBRIDGE_NUMBER_SERVER }}"
    cmds:
      - vite build

  generate-ts-proto:
    watch: true
    requires:
      vars: [PROTO_PATH]
    status:
      - grep -q "$PROTO_PATH" "$TASK_TEMP_DIR"/proto_path
    cmds:
      - for:
          var: PROTO_PATH
          split: ":"
        cmd: |
          protoc -I={{ shellQuote .ITEM }} \
            --plugin=node_modules/.bin/protoc-gen-ts_proto \
            --ts_proto_opt=esModuleInterop=true \
            --ts_proto_opt=importSuffix=.js \
            --ts_proto_out=src/lib/proto \
            {{ shellQuote .ITEM }}/*.proto
      - prettier -w src/lib/proto
      - echo "$PROTO_PATH" > "$TASK_TEMP_DIR"/proto_path
    generates:
      - src/lib/proto/*.ts
